### ISSUE TITLE
Epic: Inspect historic state

### ISSUE THREAD

**Issue by LinqLover** [LinqLover/squeak-tracedebugger#30]
- [x] Display historic states in debugger
- [ ] Inspect historic states in inspectors/explorers
  - [ ] Avoid toolbuilding for `#inspect`/`#explore` sends inside retracing simulator
  - [ ] Provide `TDBProxyForCursor` with a time index following the cursor position
